let a = parseInt(window.prompt("enter value for a"))
let b = parseInt(window.prompt("enter value for b"))
console.log(typeof(a))
console.log(typeof(b))
c = a + b
document.write("a + b = ", c)
document.write("<br>")
document.write("a - b = ", a - b)
document.write("<br>")
document.write("a * b = ", a * b)
document.write("<br>")
document.write("a / b = ", a / b)
document.write("<br>")
document.write("a % b = ", a % b)
document.write("<br>")